#!/bin/bash
printf "\n\e[0;32m🍣   Resetting Elm..."
rm -rf elm-stuff
rm -rf examples/exampleButton/elm-stuff
rm -rf examples/exampleCustomized/elm-stuff
rm -rf examples/exampleSPA/elm-stuff
rm ~/.elm/0.19.0/package/*/*/*/*.dat
printf "\n\e[0;32m🍺   Done\e[0m\n\n"
