#!/bin/bash
rm src/myStyle.elm
cd examples/exampleSPA
../../node_modules/.bin/elm-live src/Main.elm --dir=docs --path-to-elm ../../node_modules/.bin/elm --port=8003 -- --debug --output=docs/js-dev/main.js
