#!/bin/bash
cp src/MyStyle.elm.example src/MyStyle.elm
node_modules/.bin/elm-live src/Framework.elm --dir=docs --path-to-elm node_modules/.bin/elm --port=8001 -- --debug --output=docs/js-dev/framework.js
